data: 
  mnist:
     TRAIN_VALIDATION_RATIO: !!float 0.8
     N_CLASSES:  !!int 10
     N_CHANNELS: !!int 1
     IMG_SIZE:   !!int 28
  cifar10:
     TRAIN_VALIDATION_RATIO: !!float 0.8
     N_CLASSES:  !!int 10
     N_CHANNELS: !!int 3
     IMG_SIZE:   !!int 32

train:
  mnist: 
    N_EPOCHS: !!int 3
    LR: !!float 1e-2
    WEIGHT_DECAY: !!float 5e-3
    BATCH_SIZE: !!int 128
    MILE_STONE: !!seq [40, 80, 120]
  cifar10:
    N_EPOCHS: !!int 3
    LR: !!float 1e-2
    WEIGHT_DECAY: !!float 5e-3
    BATCH_SIZE: !!int 128
    MILE_STONE: !!seq [40, 80, 120]

algorithm:
  raw:

clean_model:
  mnist:
    PATH: !!str  "./clean_model/MNIST_resnet18_clean.pth"
  cifar10:
    PATH: !!str  "./clean_model/CIFAR10_resnet18_clean.pth"

misc:
  VERBOSE: !!bool true
  MONITOR_WINDOW: !!int 1